### ISSUE TITLE
Update ESLint to 9

### ISSUE THREAD

**Issue by ikuwow** [ikuwow/query_ok#653]
https://eslint.org/docs/latest/use/configure/migration-guide

## TODO

- [ ] Enable ES Modules instead of CommonJS
    * https://eslint.org/docs/latest/use/configure/language-options#specifying-javascript-options
    * Webpack config needs changes
- [ ] Migrate .eslintrc.json to eslint.config.js (flat format)
    - https://eslint.org/docs/latest/use/configure/configuration-files
- [ ] Update ESLint to 9

## Ref

https://eslint.org/docs/latest/use/configure/migration-guide
https://eslint.org/docs/latest/use/configure/configuration-files
https://nodejs.org/api/packages.html#type
